FROM registry.ci.openshift.org/ocp/builder:rhel-8-base-openshift-4.6

RUN dnf install -y iproute jq && \
      dnf clean all && \
      rm -rf /var/cache/{yum,dnf}/*

COPY ./set-static-ip /set-static-ip
COPY ./refresh-static-ip /refresh-static-ip
